### ISSUE TITLE
Extra path

### ISSUE THREAD

**Issue by awinogradov** [Yeti-or/required-path#2]
`requiredPath(requiredPath('file.js')) // -> ././file.js` ¯ \ _ (ツ) _ / ¯

**Comment by Yeti-or** [comment]
But why do you think it is a problem?

**Comment by awinogradov** [comment]
Because I can) It looks like a bug. I expected `./../file.js` or `./file.js`, but it returns path which can't be required.

**Comment by Yeti-or** [comment]
`././hello.js` could be required

**Comment by awinogradov** [comment]
Is it the same as `./../file.js`?

**Comment by Yeti-or** [comment]
```
yeti-or-osx2-2:tmp yeti-or$ tree one
one
├── index.js
└── two
    └── index.js

1 directory, 2 files
yeti-or-osx2-2:tmp yeti-or$ cd one/two
yeti-or-osx2-2:two yeti-or$ node
> require('././index.js')
two
{}
> require('././../index.js')
one
{}
```

**Comment by Yeti-or** [comment]
I mead:
`./././file.js` < - > `./file.js`
`././../file.js` < - > `../file.js`

**Comment by awinogradov** [comment]
Wow! Ok) It's not a bug) But it looks strange anyway)
